version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "4200:80"
    container_name: portfolio-frontend
    depends_on:
      - backend
    networks:
      - portfolio-network

  backend:
    image: portfolio-backend:latest
    ports:
      - "9091:9091"
    container_name: portfolio-backend
    networks:
      - portfolio-network

networks:
  portfolio-network:
    driver: bridge
